// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV4YsRihvceGKPKF95L6d-ui84zpAKbBo',
    appId: '1:434137680999:web:ab93c46d7d66a89bcb98c2',
    messagingSenderId: '434137680999',
    projectId: 'baidarg-7a917',
    authDomain: 'baidarg-7a917.firebaseapp.com',
    storageBucket: 'baidarg-7a917.appspot.com',
    measurementId: 'G-SPNNHB5TCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL_S9Fn-GpCb_2N6KP3DWb1rY-dwn7l7U',
    appId: '1:434137680999:android:06f313f1a2ae1bcacb98c2',
    messagingSenderId: '434137680999',
    projectId: 'baidarg-7a917',
    storageBucket: 'baidarg-7a917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCowNXP5ihJ1cGVEobPMBITuXsZJA40wI',
    appId: '1:434137680999:ios:dc5bfcf03772ee07cb98c2',
    messagingSenderId: '434137680999',
    projectId: 'baidarg-7a917',
    storageBucket: 'baidarg-7a917.appspot.com',
    iosClientId: '434137680999-gvq7d4hh1lllm9le9io9822lqij3ofiq.apps.googleusercontent.com',
    iosBundleId: 'com.baidarg.app',
  );
}
